[package]
name = "panic-to-result-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

[lib]
proc-macro = true
