[package]
name = "ch8-builder-code"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = { workspace = true }
syn = { workspace = true, features = ["extra-traits"] }
proc-macro2 = { workspace = true }
