[package]
name = "ch8"
version = "0.1.0"
edition = "2021"

[dependencies]
ch8-builder-macro = { path = "./builder-macro" }
analyze = { path = "./analyze" }

[dev-dependencies]
trybuild.workspace = true
